The 7-base_geometry module
==========================

Using BaseGeometry
--------------------------

Importing class from the module:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


Passing a string argument:
    >>> bg.integer_validator("name", "Mike")
    Traceback (most recent call last):
              ...
    TypeError: name must be an integer

Passing zero as an argument:
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
              ...
    ValueError: age must be greater than 0

Passing negative integer as argument:
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
              ...
    ValueError: distance must be greater than 0

Check for area:
    >>> bg = BaseGeometry()
    >>> bg.area()
    Traceback (most recent call last):
              ...
    Exception: area() is not implemented

Passing a boolean as argument:
    >>> bg.integer_validator("distance", True)
    Traceback (most recent call last):
              ...
    TypeError: distance must be an integer

Passing a tuple as argument:
    >>> bg.integer_validator("age", (3,))
    Traceback (most recent call last):
              ...
    TypeError: age must be an integer

Passing a list as argument:
    >>> bg.integer_validator("distance", [2])
    Traceback (most recent call last):
              ...
    TypeError: distance must be an integer

Passing a set as argument:
    >>> bg.integer_validator("age", {1, 3})
    Traceback (most recent call last):
              ...
    TypeError: age must be an integer

Passing None as argument:
    >>> bg.integer_validator("name", None)
    Traceback (most recent call last):
              ...
    TypeError: name must be an integer

Passing a single argument:
    >>> bg.integer_validator("name")
    Traceback (most recent call last):
              ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

Normal use case:
    >>> bg.integer_validator("width", 89)

Passing no arguments:
    >>> bg.integer_validator()
    Traceback (most recent call last):
              ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
